name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: nasm xorriso mtools mingw-w64-i686-dev
        execute_install_scripts: true
    - name: make
      run: |
        cd free95
        chmod +x *.sh
        ./buildall.sh
        make all
    - uses: actions/upload-artifact@v4
      with:
        name: Build
        path: free95/bin/
